### ISSUE TITLE
DO NOT SUPPORT BIG SUR!!

### ISSUE THREAD

**Issue by isnowify** [Lincoln-Zhou/FFmpeg-GUI#1]
!!!!IT CANNOT RUN ON MY MAC MINI

**Comment by Lincoln-Zhou** [comment]
Please follow GitHub issues guideline and specify the following information:
* Your Mac model
* macOS system version
* Python version
* PyQt version
Also, this project has no plan for supporting Hackintosh.
This issue will be closed, open a new one if you want to.
